### ISSUE TITLE
New update, Quest/Monster loader not working

### ISSUE THREAD

**Issue by Dwyriel** [Strackeror/MHW-QuestLoader#14]
Capcom released another updated today (2023/11/14), patchnotes still unknown but modloader and most mods (at least the ones that I use) are working. Game version was bumped so mods that check game version are not being loaded.

Update: according to [this thread](https://steamcommunity.com/app/582010/discussions/0/3969421533314684772) they just changed the profanity filter list and bumped the game version. My suggesting would be to completely removed the version check to prevent those two loaders to stop working for those small updates they've been rolling out.

**Comment by Strackeror** [comment]
Aye, saw the update. 
As for the version checks, I don't want to remove them as long as the loaders are based on straight offsets, and unfortunately some of the offsets aren't easily found at runtime, at least not through simple AoBs.

**Comment by Dwyriel** [comment]
I completely understand, but maybe implementing a middle term between removing it and having it hard coded would be good. Maybe another option in the config file that would be used to skip the version check if true (set to false by default) so those small version changes that do not make any meaningful modifications to the binary wouldn't just brick the mods and require changes directly to the binary (using a hex editor) or to the source files.

Also closing this issue as it's been fixed, thanks for the fast work, you and fexty ;)
